### ISSUE TITLE
Permissions not set properly on clean install

### ISSUE THREAD

**Issue by ootjersb** [hydex80/presence_detection_domoticz_fritzbox#1]
After a clean install the permissions on presence_detection.sh are:
-rw-r--r-- 1 root root 11688 Feb 26 15:12 presence_detection.sh
As a consequence it cannot be executed.

Either include a chmod 755 presence_detection.sh in the script or installation steps.

**Comment by hydex80** [comment]
fixed used sudo chmod +x presence_detection in script 

now in branche beta.
