### ISSUE TITLE
iOS 14 changes MAC adresses

### ISSUE THREAD

**Issue by GewoonGijs** [hydex80/presence_detection_domoticz_fritzbox#2]
Too Bad, iOS 14 changes MAC adresses as a security measure. Seems tht we cannot do anything about that easily. Furthermore I see different MAC adresses on 2.4GHz and 5GHz bands.

Aaaargh.

**Comment by hydex80** [comment]
You can disable it for a certain network. 

To Disable MAC Randomization in Android 10 & Apple iOS, complete the steps below: 

**Google Pixel / Motorola / Other Androids:**
Open the Settings app
Select Network and Internet
Select WiFi
Connect to the Wireless network
Tap the gear icon next to the current connection
Select Advanced
Select Privacy
Select "Use device MAC"

**Samsung Galaxy:**
Navigate to "Settings"
Select "Connections"
Select "WiFi"
Select "the Wireless Network you wish to connect to"
Tap the gear shaped icon next to the network you connected to
Select "Advanced"
On the next screen there is a menu labeled "MAC Address Type".
Tap on "MAC Address Type"

**Select “Use Phone/Device MAC”**
Apple iOS 14 & Later: 
Ensure your device is connected to a Wi--Fi Network
Open the "Settings app", then tap "Wi-Fi"
Tap the "information button" next to your Plume network 
Tap on the "Use private Address" toggle to turn it off
After, a privacy warning will pop-up
